#!/bin/bash
set -euo pipefail

MYSQLARGS='--user=root --password=root'

mysql $MYSQLARGS -e 'CREATE DATABASE IF NOT EXISTS test_db DEFAULT CHARACTER SET = utf8mb4;'
mysql test_db $MYSQLARGS < sql/create-tables.sql
