name: pre-commit
on:
  push:
  pull_request:
jobs:
  pre-commit:
    name: pre-commit (ubuntu-latest, 3.7)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Update pip, setuptools, and wheel
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install pylint
        run: python -m pip install pylint==2.5.3
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0
        #with:
        #  token: ${{ secrets.GITHUB_TOKEN }}
