name: Release
on:
  release:
    types:
      - released
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
      - name: Install with dependencies and build
        run: |
          poetry install
          poetry show
          poetry build
      - name: Upload assets
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: dist/*
