name: Release
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v6
      - name: Install with dependencies and build
        run: |
          poetry install
          poetry show
          poetry build
      - name: Upload assets
        uses: shogo82148/actions-upload-release-asset@v1.3.0
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*
